### PR TITLE
pt_BR translation

### PR DESCRIPTION
**Pull request by lennonjesus**
Work-in-progress Brazilian Portuguese version. Maybe someone help me with missing translations and reviews.

### CODE REVIEW

**Comment by hackergrrl** [comment]
Oh wow! Fantastic work @lennonjesus :star2:! Thank you for this heruclean effort. I'm sure we have a few Brazillian readers around here..

**Comment by vmesel** [comment]
@lennonjesus I can help u!

**Comment by lennonjesus** [comment]
Great, @vmesel! 

Please, [fork](https://github.com/lennonjesus/art-of-readme/blob/master/README-pt-BR.md) and submit your PRs!

**Review by vmesel — COMMENTED** [review]
Apparently this text is translated into the correct form of the portuguese language.

Aparentemente está tudo dentro das conformidades da Lingua Portuguesa!

**Comment by lennonjesus** [comment]
I hope we can help some Brazilian readers, @noffle. o/

**Comment by hackergrrl** [comment]
Wow! You are truly a :star2: @lennonjesus! Thank you so much for your awesome work in creating this translation. :grinning: 

I added a bit for your work under the _Credits_ section, too.

**Pull request merged**
