### PR TITLE
adding links to contributors' profile

### PR DESCRIPTION
**Pull request by KrishMunot**

### CODE REVIEW

**Comment by hackergrrl** [comment]
Aw, thank you @KrishMunot! Add yourself to that list and I'll merge this right away. :star2:

**Comment by KrishMunot** [comment]
@noffle awesome! Just did that :smile:

**Comment by hackergrrl** [comment]
I think you'll need to rebase -- I went and broke things earlier today. :grinning:

**Comment by hackergrrl** [comment]
I went ahead and patched your changes into master. Thanks again for this! :horse:

**Comment by KrishMunot** [comment]
Ahha! Cool! Can you add me to the contributors list as well? 
Thanks! 👍

**Comment by hackergrrl** [comment]
Ah ha, right! Thanks for reminding me: https://github.com/noffle/art-of-readme/commit/b875e21874068fa2e8a1701dcba079cf6d803cd8

**Pull request closed without merging**
