### PR TITLE
Revise punctuations in Chinese translation

### PR DESCRIPTION
**Pull request by BrettDong**
Edit all punctuations into full width style.

### CODE REVIEW

**Comment by BrettDong** [comment]
Oops, collide with #18 .

**Comment by hackergrrl** [comment]
Ping @qihaiyan -- how does this look to you? I am woefully unqualified to provide you with any feedback, @BrettDong. :grinning:

**Review by qihaiyan — APPROVED** [review]
the reformat is really good.

**Comment by hackergrrl** [comment]
Woohoo! Thank you @BrettDong for sharing this, and thank you @qihaiyan for looking it over. :star2:

Would it be all right with y'all if I pinged you on future PRs to the Chinese translation? I have no ability to offer feedback and you two seem to be very on the ball. :heart:

**Comment by hackergrrl** [comment]
One more thing before I merge: @BrettDong, would you feel up to adding yourself to the English and Chinese _Credits_ section as well?

**Comment by BrettDong** [comment]
> Would it be all right with y'all if I pinged you on future PRs to the Chinese translation?

No problem for me with pleasure.

**Comment by BrettDong** [comment]
OK, I rebased my branch, so merge conflicts are solved.

**Comment by hackergrrl** [comment]
Thank you @BrettDong! :pray:

**Pull request merged**
