### PR TITLE
Modify the error text

### PR DESCRIPTION
**Pull request by hejianxian**
注视 to 注释

### CODE REVIEW

**Comment by hackergrrl** [comment]
What do you think on this, @qihaiyan? I have zero fluency in Chinese and would :heart: any help reviewing these PRs!

**Review by qihaiyan — APPROVED** [review]
yes, you are right, it's my fault.

**Comment by hackergrrl** [comment]
Thanks @Alex-fun, and thanks @qihaiyan for reviewing! :star2: 

@Alex-fun, do you feel like adding yourself to the _Credits_ section of both documents before I merge?

**Comment by hejianxian** [comment]
@noffle 👌

**Comment by hackergrrl** [comment]
+100! :tada:

**Pull request merged**
