### PR TITLE
doc: add Traditional Chinese version

### PR DESCRIPTION
**Pull request by AlanSyue**
I added the Traditional Chinese version to make it easier for Taiwanese readers to read this article.

I also fixed the wrong order number for the footnote section.

Thanks for your awesome article!

### CODE REVIEW

**Comment by hackergrrl** [comment]
Thanks @AlanSyue for the time & energy. 💙 

I'd like to get a thumbs-up from another reader who knows the language, just as a sanity check (since I don't have the language skillset to review it myself).

**Comment by AlanSyue** [comment]
> Thanks @AlanSyue for the time & energy. 💙
> 
> I'd like to get a thumbs-up from another reader who knows the language, just as a sanity check (since I don't have the language skillset to review it myself).

I think I can invite some Taiwanese readers to review this Traditional Chinese version!

**Comment by AlanSyue** [comment]
@hackergrrl Is there any problem with this PR?

**Comment by hackergrrl** [comment]
> @hackergrrl Is there any problem with this PR?

I don't know: it's not a language I'm familiar with. :)   If you can get another github user to review it and say it looks good, I'll merge it in.

**Comment by AlanSyue** [comment]
> > @hackergrrl Is there any problem with this PR?
> 
> I don't know: it's not a language I'm familiar with. :) If you can get another github user to review it and say it looks good, I'll merge it in.

OK, got it, thanks!

**Comment by jamie328** [comment]
I love @AlanSyue contribution. This traditional Chinese version let me know about history and how to write a good **README**. Well done! @AlanSyue 
BTW, I love this sentence that your documentation is complete when someone can use your module without ever having to look at its code.

**Pull request merged**
