### PR TITLE
zh: Some reviews on punctuation

### PR DESCRIPTION
**Pull request by Artoria2e5**
Contents before line 114 (um yes, only a half) are loosely reviewed for punctuation. I only fixed phrasing problems I found when reading the text to find proper punctuations, so many errors remain.

It appears that the original translator(s) has an English parser that forces a token break on links. Meh.

To those using git blame: Don't blame me for writing bad translations. I am mostly adding spaces and changing punctuations.

### CODE REVIEW

**Comment by hackergrrl** [comment]
Thank you very much @Artoria2e5 for the :heart:!

Pinging the esteemed @qihaiyan and @BrettDong :grinning:

**Comment by qihaiyan** [comment]
To be honest, my english is not good. The fix made by @Artoria2e5 is much better and more suitable than mine original translation.
@Artoria2e5 我觉得你比我更适合翻译这篇文章，你要有时间的话把翻译错误都改掉吧，或者你觉得实在是没法改，重新翻译也行。

**Comment by Artoria2e5** [comment]
@qihaiyan Hmm well. It's not about language skills; it's about you assuming that links break sentence flows. Looking at the rendered result before working on the source should help -- the link syntax is indeed hard to scan around.

嘛不是语言水平问题啦。主要是你总是盯着源码看，本来连在一起的东西被链接切开了。翻译前看看渲染结果读一读，或者手边开个预览窗口什么的应该会有些帮助。

**Comment by qihaiyan** [comment]
@Artoria2e5 "本来连在一起的东西被链接切开了"没太看明白什么意思，是指链接的前后多了空格吗？我看没有出现换行的情况。我编辑的时候是用macdown这个软件，自带着预览窗口的。编辑完后直接拷贝到github了。可能存在语法兼容的问题。

**Comment by Artoria2e5** [comment]
@qihaiyan “句子被链接切开”是指链接插在里面读原文可能不那么直观的情况。我看到现在的翻译经常把链接误解为专有名词或者很特别的东西，于是直接漏翻甚至漏理解：

> 一些有经验的Node开发者合力创建了高质量模块的列表[curated lists](https://github.com/sindresorhus/awesome-nodejs)，
> 
> Some experienced Node developers band together to create [curated lists](https://github.com/sindresorhus/awesome-nodejs) of quality modules.
> 
> ---
> 
> 当然新的开发者还是可以用npm自带的 [search](https://npmjs.org) 功能。 _这个我没改到_
> 
> Of course there is also npm's built-in [search](https://npmjs.org) functionality: a safe default, and the usual port of entry for new developers.
> 
> ---
> 
> 结果表明[monks](http://perlmonks.org) Perl 社区在编写[高质量 README**s**](http://search.cpan.org/~kane/Archive-Tar/lib/Archive/Tar.pm)方面很有经验。 _复数 s 要切掉啊……_
> 
> It so turns out that the [monks](http://perlmonks.org) of the Perl community indeed have a great deal of experience in writing [quality READMEs](http://search.cpan.org/~kane/Archive-Tar/lib/Archive/Tar.pm).
> 
> 后面倒是正确地把 monks 翻了，叫做“圣僧”。

**Comment by qihaiyan** [comment]
@Artoria2e5 第二个问题里的search是故意保留的，有时候全翻译成中文反而会看不懂。。。
其它两个确实是有问题，谢谢你的指正。

**Comment by qihaiyan** [comment]
hi, @noffle , would you mind to accept this PR? the fix is ok.

**Comment by hackergrrl** [comment]
:star2:

**Pull request merged**
