### PR TITLE
Fix miscellaneous typographic errors

### PR DESCRIPTION
**Pull request by thenickcox**
This commit fixes three types of typographic errors. Listed in
descending order of frequency, the changes are:
1. Change two hyphens to em dashes
   ([reference](http://practicaltypography.com/hyphens-and-dashes.html))
2. In a quotation, place punctuation inside the quotation
3. Other miscellaneous fixes (Italicize _bona fide_, etc.)

### CODE REVIEW

**Comment by hackergrrl** [comment]
Thanks for taking the time and consideration, @thenickcox! :star2: 

I'm 100% down with your changes, except for the em dashes. I _know_ you're technically correct, but I'm a curmudgeonly person who prefers ASCII as much as possible for written documents. I suspect this is because I don't know how to easily write em dashes on my system -- or on any other system I may write on -- and don't want my document to become any more complicated for me to make changes to. If you're cool with reverting the em dashes back to `--` I'd be more than pleased to merge in your changes! :tada:

**Review by luckhelena — APPROVED** [review]

**Comment by Artoria2e5** [comment]
@noffle Hmm, how about going entities and using `&mdash;`?

**Comment by thenickcox** [comment]
@noffle Thanks for the feedback. It's clear, based on your response, that em dashes are a part of your writing style. I'll revert the changes back to `--` for now to preserve your original intent.

**Comment by thenickcox** [comment]
@noffle This should be ready to go.

**Comment by lennonjesus** [comment]
Hi, @thenickcox.

Please, can you squash your commits?

**Comment by thenickcox** [comment]
@lennonjesus Squashed. Thanks.

**Comment by hackergrrl** [comment]
Awesome work @thenickcox! I'll add you to the credits, too..

**Pull request merged**
