### PR TITLE
es_ES translation

### PR DESCRIPTION
**Pull request by jabiinfante**
Text translated to spanish.

### CODE REVIEW

**Comment by hackergrrl** [comment]
Thank you very much @jabiinfante! Is this ready to go? A couple of things:
1. Add your name + a short paragraph like the ones for the other translations to the _Credits_ section of both the `en` and `es` READMEs. :grinning: 
2. Add a link at the top of the main `README.md` for your translation.
3. Squash your commits down into one.

Thanks again! :pray:

**Comment by jabiinfante** [comment]
There it goes!

Allthought README.md is conflicting.

**Comment by hackergrrl** [comment]
@jabiinfante nice! Do you know how to rebase from the command line?

**Comment by jabiinfante** [comment]
@noffle,  I have tried but I am not sure I got it right...

**Comment by jabiinfante** [comment]
@noffle Now it's ready to merge ;)

**Comment by hackergrrl** [comment]
@jabiinfante amazing work! Thank you so much! :star2:

**Pull request merged**
