### PR TITLE
Grammar fixes

### PR DESCRIPTION
**Pull request by wytrych**
- Remove a duplicated sentence
- Change a sentence that felt not in place and use it's information in parens instead

### CODE REVIEW

**Comment by wytrych** [comment]
Please merge

**Comment by hackergrrl** [comment]
Hey @wytrych! Thank you for the effort here, but I'm not sure I'm 100% with your change as-is. I still _do_ want to express that there are strong opinons on cbs/promises. I'm going to close this, but thank you for being aware of this sort of awkward wording -- I'll think on it some more. :star2:

**Comment by wytrych** [comment]
There is still a duplicate sentence there though.

**Comment by hackergrrl** [comment]
Ah ha, I see it now! Fixed. Thank you. :star2:

**Pull request closed without merging**
