### PR TITLE
Improve a sentence in zh translation

### PR DESCRIPTION
**Pull request by aquarhead**

### CODE REVIEW

**Comment by hackergrrl** [comment]
Thanks @aquarhead! :star2: 

Pinging the talented @qihaiyan and @BrettDong. :grinning:

**Comment by qihaiyan** [comment]
Thanks @aquarhead, but this commit conflicts with #32 , how do you think @Artoria2e5 ?

**Comment by Artoria2e5** [comment]
1. ideographic comma (backwards comma, 顿号, 、)
2. 其实可以部分保留原来的翻法（挺顺口的这不），把“做”改成“写”就差不多了。

**Comment by BrettDong** [comment]
Merge conflicts needs to be resolved.

**Pull request closed without merging**
